# Generated by Django 5.1.4 on 2024-12-26 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_libros', '0002_post_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='estado',
            field=models.CharField(choices=[('B', 'Borrador'), ('P', 'Publicado')], max_length=50),
        ),
    ]
